"use client";

import { useEffect, useState } from "react";

export default function ParallaxCarousel() {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div className="relative w-full bg-[#030712] text-white selection:bg-emerald-500/30 overflow-x-hidden">
      
      {/* --- BACKGROUND LAYER: DYNAMIC GLOWS --- */}
      <div className="fixed inset-0 pointer-events-none">
        <div 
          className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] bg-emerald-600/10 rounded-full blur-[120px] animate-pulse"
          style={{ transform: `translateY(${scrollY * 0.1}px)` }}
        />
        <div 
          className="absolute bottom-[-10%] right-[-10%] w-[400px] h-[400px] bg-indigo-600/10 rounded-full blur-[100px]"
          style={{ transform: `translateY(${scrollY * -0.05}px)` }}
        />
      </div>

      {/* --- MAIN PARALLAX CONTENT --- */}
      <div className="relative z-10">
        
        {/* HERO SECTION */}
        <section className="min-h-screen flex flex-col items-center justify-center px-6 pt-24">
          
          <div className="relative flex items-center justify-center w-full max-w-4xl">
            
            {/* 1. ANIMATED HUD ELEMENTS (Generated by Code) */}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
              {/* Outer Spinning Ring */}
              <div className="w-[320px] h-[320px] md:w-[550px] md:h-[550px] border border-white/5 rounded-full animate-[spin_30s_linear_infinite]" />
              {/* Inner Emerald Accent Ring */}
              <div className="absolute w-[300px] h-[300px] md:w-[480px] md:h-[480px] border-t-2 border-emerald-500/20 rounded-full animate-[spin_15s_linear_infinite]" />
              {/* Pulsing Data Nodes */}
              <div className="absolute top-1/4 left-1/4 w-2 h-2 bg-emerald-400 rounded-full animate-ping" />
              <div className="absolute bottom-1/3 right-1/4 w-1.5 h-1.5 bg-indigo-400 rounded-full animate-ping [animation-delay:1s]" />
            </div>

            {/* 2. THE PORTRAIT (The anchor of the design) */}
            <div className="relative z-20 w-[300px] md:w-[450px] transition-all duration-700 hover:scale-[1.03]">
              {/* We use a mask to fade the bottom into the background */}
              <div style={{
                maskImage: 'linear-gradient(to bottom, black 80%, transparent 100%)',
                WebkitMaskImage: 'linear-gradient(to bottom, black 80%, transparent 100%)'
              }}>
                <img 
                  src="/assets/images/blessing-hero.png" 
                  alt="Blessing Okon"
                  className="w-full h-auto block drop-shadow-[0_0_80px_rgba(16,185,129,0.15)]"
                />
              </div>
            </div>

            {/* 3. FLOATING INTERACTIVE CARDS (Responsive & Fluid) */}
            
            {/* Project Management Badge */}
            <div 
              className="absolute -left-4 md:-left-20 top-1/4 z-30 p-4 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl animate-bounce [animation-duration:6s]"
              style={{ transform: `translateY(${scrollY * 0.12}px)` }}
            >
              <div className="flex items-center gap-3 mb-2">
                <div className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-[10px] font-mono font-bold tracking-[0.2em] text-emerald-400 uppercase">Operations</span>
              </div>
              <p className="text-[11px] text-neutral-300 font-medium leading-tight">Data Integrity: 100%<br/>Stakeholder Ready</p>
            </div>

            {/* Creative Design Badge */}
            <div 
              className="absolute -right-6 md:-right-16 bottom-1/4 z-30 p-5 bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl animate-bounce [animation-duration:8s] [animation-delay:1s]"
              style={{ transform: `translateY(${scrollY * -0.08}px)` }}
            >
              <div className="flex flex-col items-center gap-2">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#818cf8" strokeWidth="1.5">
                  <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
                </svg>
                <span className="text-[9px] font-black text-indigo-300 uppercase tracking-widest text-center">UI/UX & Fashion<br/>Strategy</span>
              </div>
            </div>
          </div>

          {/* TEXT CONTENT LAYER */}
          <div className="mt-12 text-center max-w-5xl px-4">
            <h1 className="text-5xl md:text-[100px] font-black tracking-tighter uppercase leading-[0.9] mb-6">
              BLESSING <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 via-teal-200 to-indigo-400">OKON</span>
            </h1>
            <p className="text-neutral-400 text-lg md:text-2xl font-light max-w-3xl mx-auto leading-relaxed">
              An <span className="text-white font-medium">Administrative Support Specialist</span> and 
              <span className="text-white font-medium"> Project Manager</span> bridging the gap between 
              <span className="text-emerald-400 font-semibold italic"> Operational Efficiency </span> 
              and <span className="text-indigo-300"> Creative Excellence</span>.
            </p>
            
            <div className="mt-10 flex flex-wrap justify-center gap-4">
              <button onClick={() => window.location.href = '#trajectory'} className="px-10 py-4 bg-emerald-600 rounded-full font-bold text-sm tracking-widest hover:bg-emerald-500 hover:scale-105 transition-all shadow-[0_0_20px_rgba(16,185,129,0.4)]">
                VIEW PORTFOLIO
              </button>
              <button onClick={() => window.location.href = 'mailto:beeokon68@gmail.com'} className="px-10 py-4 bg-white/5 border border-white/10 rounded-full font-bold text-sm tracking-widest hover:bg-white/10 transition-all">
                GET IN TOUCH
              </button>
            </div>
          </div>
        </section>

        {/* --- SECTION 2: THE SKILLS BENTO (Expanding Section) --- */}
        <section className="py-32 px-6">
          <div className="max-w-6xl mx-auto">
            <div className="flex flex-col md:flex-row justify-between items-end mb-12 gap-6">
              <h2 className="text-4xl md:text-6xl font-bold tracking-tighter">VERSATILE <br/>EXPERTISE</h2>
              <p className="text-neutral-500 max-w-xs text-sm">A synthesis of linguistic precision, organizational leadership, and visual storytelling.</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {/* Admin Card */}
              <div className="p-10 bg-white/5 rounded-[2.5rem] border border-white/10 hover:border-emerald-500/40 transition-all group overflow-hidden relative">
                <div className="absolute -right-4 -top-4 w-24 h-24 bg-emerald-500/5 rounded-full blur-2xl group-hover:bg-emerald-500/20 transition-all" />
                <h3 className="text-emerald-400 font-mono text-xs mb-6 tracking-widest uppercase">Admin Support</h3>
                <h4 className="text-3xl font-bold mb-4">Operations</h4>
                <p className="text-neutral-400 leading-relaxed text-sm">Expert in NOMIS 3.0 and USAID project reporting. Streamlining complex data workflows with 100% accuracy.</p>
              </div>

              {/* PM Card (Featured) */}
              <div className="p-10 bg-emerald-500 rounded-[2.5rem] text-black hover:scale-[1.02] transition-transform shadow-[0_20px_40px_rgba(16,185,129,0.2)]">
                <h3 className="font-mono text-xs mb-6 tracking-widest uppercase opacity-70">Core Proficiency</h3>
                <h4 className="text-3xl font-bold mb-4">Project Mgmt.</h4>
                <p className="font-medium leading-relaxed text-sm">Google-Certified lifecycle management. Coordinating stakeholders, timelines, and deliverables across virtual platforms.</p>
              </div>

              {/* Design Card */}
              <div className="p-10 bg-white/5 rounded-[2.5rem] border border-white/10 hover:border-indigo-500/40 transition-all group overflow-hidden relative">
                <div className="absolute -right-4 -top-4 w-24 h-24 bg-indigo-500/5 rounded-full blur-2xl group-hover:bg-indigo-500/20 transition-all" />
                <h3 className="text-indigo-300 font-mono text-xs mb-6 tracking-widest uppercase">Creative Core</h3>
                <h4 className="text-3xl font-bold mb-4">Visual Design</h4>
                <p className="text-neutral-400 leading-relaxed text-sm">Bringing a linguistic lens to UI/UX and Fashion design. Crafting brand identities that communicate and convert.</p>
              </div>
            </div>
          </div>
        </section>
{/* --- SECTION 3: PROFESSIONAL MILESTONES (Timeline) --- */}
<section id="trajectory" className="py-32 bg-[#030712] relative overflow-hidden">
  <div className="max-w-6xl mx-auto px-6">
    <div className="mb-20">
      <h2 className="text-emerald-500 font-mono text-sm tracking-[0.3em] uppercase mb-4">Trajectory</h2>
      <h3 className="text-5xl md:text-7xl font-bold tracking-tighter">IMPACT & <br/>EXPERIENCE.</h3>
    </div>

    <div className="relative border-l border-white/10 ml-4 md:ml-0 md:pl-0">
      
      {/* 1. MOST RECENT: The DreamPOD Place (2024 — 2025) */}
      <div className="mb-24 relative pl-10 md:pl-20 group">
        <div className="absolute left-[-5px] top-2 w-2.5 h-2.5 bg-indigo-500 rounded-full shadow-[0_0_15px_rgba(99,102,241,1)]" />
        
        <div className="flex flex-col md:flex-row md:items-center gap-4 mb-4">
          <span className="text-indigo-400 font-mono text-sm font-bold">2024 — 2025</span>
          <h4 className="text-2xl md:text-3xl font-bold text-white group-hover:text-indigo-400 transition-colors">The DreamPOD Place</h4>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <p className="text-neutral-400 leading-relaxed">
              Serving as the <span className="text-white">Administrative Support Officer</span>. I manage high-traffic front desk operations and internal communications while doubling as the lead creative for training materials.
            </p>
            <div className="flex flex-wrap gap-2">
              <span className="px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 rounded-full text-[10px] text-indigo-400 font-bold uppercase">Admin Ops</span>
              <span className="px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 rounded-full text-[10px] text-indigo-400 font-bold uppercase">Event Coordination</span>
              <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] text-neutral-400 uppercase">Canva / Design</span>
            </div>
          </div>
          
          <div 
            className="p-6 bg-indigo-500/5 border border-indigo-500/20 rounded-2xl shadow-2xl backdrop-blur-sm"
            style={{ transform: `translateY(${scrollY * 0.04}px)` }}
          >
            <div className="text-xs font-mono text-indigo-400 mb-2">DYNAMIC ROLE:</div>
            <p className="text-sm italic text-neutral-300">"Successfully coordinated training sessions and events by blending organizational scheduling with custom visual assets."</p>
          </div>
        </div>
      </div>

      {/* 2. Heal the Land Initiative (2023 — 2024) */}
      <div className="mb-24 relative pl-10 md:pl-20 group">
        <div className="absolute left-[-5px] top-2 w-2.5 h-2.5 bg-emerald-500 rounded-full shadow-[0_0_15px_rgba(16,185,129,1)]" />
        
        <div className="flex flex-col md:flex-row md:items-center gap-4 mb-4">
          <span className="text-emerald-500 font-mono text-sm font-bold">2023 — 2024</span>
          <h4 className="text-2xl md:text-3xl font-bold text-white group-hover:text-emerald-400 transition-colors">Heal the Land Initiative / CCCRN</h4>
        </div>
        
        <div className="grid md:grid-cols-2 gap-8 items-start">
          <div className="space-y-4">
            <p className="text-neutral-400 leading-relaxed">
              <span className="text-white">Data Entry Clerk & Administrative Assistant</span> for the USAID-funded ICHSSA Lot 1 project. Managed sensitive household data and supported M&E reporting.
            </p>
            <div className="flex flex-wrap gap-2">
              <span className="px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 rounded-full text-[10px] text-emerald-400 font-bold uppercase">NOMIS 3.0</span>
              <span className="px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 rounded-full text-[10px] text-emerald-400 font-bold uppercase">USAID Reporting</span>
              <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] text-neutral-400 uppercase">Data Quality</span>
            </div>
          </div>
          
          <div 
            className="p-6 bg-emerald-500/5 border border-emerald-500/20 rounded-2xl shadow-2xl backdrop-blur-sm"
            style={{ transform: `translateY(${scrollY * 0.02}px)` }}
          >
            <div className="text-xs font-mono text-emerald-500 mb-2">PRECISION IMPACT:</div>
            <p className="text-sm italic text-neutral-300">"Ensured 100% data accuracy for vulnerable household enrollments and service delivery tracking."</p>
          </div>
        </div>
      </div>

      {/* 3. Ndifreke Ukpe & Co (2021 — 2023) */}
      <div className="relative pl-10 md:pl-20 group">
        <div className="absolute left-[-5px] top-2 w-2.5 h-2.5 bg-neutral-600 rounded-full" />
        
        <div className="flex flex-col md:flex-row md:items-center gap-4 mb-4">
          <span className="text-neutral-500 font-mono text-sm font-bold">2021 — 2023</span>
          <h4 className="text-2xl md:text-3xl font-bold text-white group-hover:text-neutral-400 transition-colors">Ndifreke Ukpe & Co</h4>
        </div>

        <div className="space-y-4 max-w-2xl">
          <p className="text-neutral-400 leading-relaxed">
            <span className="text-white">Legal Front Desk Officer</span>. Managed confidential legal files, court-related scheduling, and professional correspondence for a fast-paced solicitors' firm.
          </p>
          <div className="flex flex-wrap gap-2">
            <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] text-neutral-300 uppercase">Case Management</span>
            <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] text-neutral-300 uppercase">Client Relations</span>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

{/* --- SECTION 4: THE TECHNICAL ARSENAL --- */}
<section className="py-32 bg-white text-black rounded-[4rem] relative z-20 shadow-[0_-20px_50px_rgba(0,0,0,0.1)]">
  <div className="max-w-6xl mx-auto px-6">
    <div className="flex flex-col md:flex-row justify-between items-start mb-16 gap-8">
      <div className="max-w-xl">
        <h2 className="text-emerald-600 font-mono text-sm tracking-widest uppercase mb-4">Stack & Systems</h2>
        <h3 className="text-5xl md:text-7xl font-black tracking-tighter leading-none">THE TOOLS <br/>OF IMPACT.</h3>
      </div>
    </div>

    <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
      
      {/* Category: Project & Task Mgmt */}
      <div className="md:col-span-2 p-8 bg-neutral-50 rounded-[2.5rem] border border-neutral-100 group hover:bg-emerald-600 transition-all duration-500">
        <h4 className="font-bold text-xl mb-8 group-hover:text-white transition-colors">Project Management</h4>
        <div className="grid grid-cols-2 gap-4">
          {[
            { name: 'Trello', slug: 'trello' },
            { name: 'Asana', slug: 'asana' },
            { name: 'ClickUp', slug: 'clickup' },
            { name: 'Notion', slug: 'notion' }
          ].map((tool) => (
            <div key={tool.name} className="flex items-center gap-3 p-4 bg-white rounded-2xl shadow-sm group-hover:bg-emerald-500/50 transition-all">
              <img src={`https://cdn.simpleicons.org/${tool.slug}/000000`} className="w-5 h-5 group-hover:invert transition-all" alt={tool.name} />
              <span className="text-xs font-bold group-hover:text-white">{tool.name}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Category: Data & Operations */}
      <div className="md:col-span-2 p-8 bg-neutral-900 rounded-[2.5rem] group hover:shadow-[0_20px_40px_rgba(16,185,129,0.3)] transition-all duration-500">
        <h4 className="font-bold text-xl mb-8 text-white">Data & Operations</h4>
        <div className="grid grid-cols-2 gap-4">
          {[
            { name: 'NOMIS 3.0', url: 'custom' }, 
            { name: 'MS Excel', url: '/assets/images/ms_excel.svg' },
            { name: 'G-Sheets', url: 'https://cdn.simpleicons.org/googlesheets/34d399' },
            { name: 'Workspace', url: 'https://cdn.simpleicons.org/google/34d399' }
          ].map((tool) => (
            <div key={tool.name} className="flex items-center gap-3 p-4 bg-white/5 border border-white/10 rounded-2xl group-hover:bg-emerald-500 transition-all">
              {tool.url === 'custom' ? (
                <div className="w-5 h-5 border-2 border-emerald-400 rounded-sm flex items-center justify-center text-[8px] font-bold text-emerald-400 group-hover:text-black group-hover:border-black">N3</div>
              ) : (
                <img src={tool.url} className="w-5 h-5 group-hover:brightness-0 transition-all" alt={tool.name} />
              )}
              <span className="text-xs font-bold text-neutral-300 group-hover:text-black">{tool.name}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Category: Creative Suite */}
      <div className="md:col-span-2 p-8 bg-neutral-50 rounded-[2.5rem] border border-neutral-100 group hover:bg-indigo-600 transition-all duration-500">
        <h4 className="font-bold text-xl mb-8 group-hover:text-white transition-colors">Creative Suite</h4>
        <div className="grid grid-cols-2 gap-4">
          {[
            { name: 'Figma', url: 'https://cdn.simpleicons.org/figma/000000' },
            { name: 'CorelDraw', url: 'https://cdn.simpleicons.org/coreldraw/000000' },
            { name: 'Canva', url: '/assets/images/canva.svg' },
            { name: 'Adobe Suite', url: 'https://www.vectorlogo.zone/logos/adobe/adobe-icon.svg' }
          ].map((tool) => (
            <div key={tool.name} className="flex items-center gap-3 p-4 bg-white rounded-2xl shadow-sm group-hover:bg-indigo-400 transition-all">
              <img src={tool.url} className="w-5 h-5 group-hover:invert group-hover:brightness-0 transition-all" alt={tool.name} />
              <span className="text-xs font-bold group-hover:text-white">{tool.name}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Category: Communication */}
      <div className="md:col-span-2 p-8 bg-neutral-50 rounded-[2.5rem] border border-neutral-100 group hover:bg-neutral-800 transition-all duration-500">
        <h4 className="font-bold text-xl mb-8 group-hover:text-white transition-colors">Communication</h4>
        <div className="grid grid-cols-2 gap-4">
          {[
            { name: 'Slack', url: 'assets/images/slack.svg' },
            { name: 'Zoom', url: 'https://cdn.simpleicons.org/zoom/000000' },
            { name: 'MS Teams', url: 'assets/images/ms_teams.svg' },
            { name: 'Mendeley', url: 'https://cdn.simpleicons.org/mendeley/000000' }
          ].map((tool) => (
            <div key={tool.name} className="flex items-center gap-3 p-4 bg-white rounded-2xl shadow-sm group-hover:bg-white/20 transition-all">
              <img src={tool.url} className="w-5 h-5 group-hover:invert group-hover:brightness-0 transition-all" alt={tool.name} />
              <span className="text-xs font-bold group-hover:text-white">{tool.name}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  </div>
</section>

{/* --- SECTION 5: THE LINGUISTIC EDGE (Education & Strategy) --- */}
<section className="py-32 bg-[#030712] relative overflow-hidden">
  {/* Subtle Background Text for a "Linguistic" vibe */}
  <div className="absolute top-0 left-0 w-full h-full flex items-center justify-center opacity-[0.02] pointer-events-none select-none">
    <span className="text-[20vw] font-black">BLESSING</span>
  </div>

  <div className="max-w-6xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 gap-20 items-center">
    
    {/* Left Side: The Degree & Philosophy */}
    <div className="relative z-10">
      <h2 className="text-emerald-500 font-mono text-xs tracking-[0.4em] uppercase mb-6">Intellectual Foundation</h2>
      <h3 className="text-5xl md:text-7xl font-bold tracking-tighter mb-8 text-white">LINGUISTIC <br/>PRECISION.</h3>
      
      <div className="space-y-6 max-w-lg">
        <p className="text-neutral-400 text-lg leading-relaxed">
          With a <span className="text-white font-medium">Bachelor of Arts in Linguistics</span> from the University of Uyo, Blessing approaches administration through the lens of structural clarity.
        </p>
        <p className="text-neutral-400 leading-relaxed">
          She doesn't just process files; she ensures the <span className="text-emerald-400 italic">integrity of language</span>—making her an indispensable asset for legal documentation and complex stakeholder reporting.
        </p>
      </div>

      <div className="mt-12 inline-flex items-center gap-6 p-4 bg-white/5 rounded-2xl border border-white/10">
        <div className="w-14 h-14 bg-emerald-500 rounded-xl flex items-center justify-center text-black">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>
        </div>
        <div>
          <h4 className="text-white font-bold uppercase tracking-widest text-xs">Degree Conferred</h4>
          <p className="text-neutral-400 text-sm">B.A. Linguistics, UniUyo</p>
        </div>
      </div>
    </div>

    {/* Right Side: The "Bridge" Skills */}
    <div className="grid gap-4">
      {[
        { 
          title: "Document Integrity", 
          desc: "Expert proofreading and semantic analysis for legal correspondence and technical data registers." 
        },
        { 
          title: "Stakeholder Bridge", 
          desc: "Translating complex project requirements into clear, actionable administrative workflows." 
        },
        { 
          title: "Information Hierarchy", 
          desc: "Using linguistic logic to organize database structures and project management boards." 
        }
      ].map((skill, i) => (
        <div key={i} className="p-8 bg-gradient-to-r from-white/5 to-transparent border-l-2 border-emerald-500/30 hover:border-emerald-500 transition-all group">
          <h5 className="text-white font-bold mb-2 group-hover:text-emerald-400 transition-colors">{skill.title}</h5>
          <p className="text-neutral-500 text-sm leading-relaxed">{skill.desc}</p>
        </div>
      ))}
    </div>

  </div>
</section>
      </div>
      {/* --- SECTION 6: THE CALL TO ACTION & FOOTER --- */}
<footer className="relative pt-32 pb-10 bg-emerald-500 text-black overflow-hidden">
  {/* Large Background Decorative Text */}
  <div className="absolute top-12 left-1/2 -translate-x-1/2 whitespace-nowrap opacity-10 pointer-events-none select-none">
    <span className="text-[22vw] font-black tracking-tighter uppercase">Available</span>
  </div>

  <div className="max-w-6xl mx-auto px-6 relative z-10">
    <div className="flex flex-col items-center text-center">
      <h2 className="text-6xl md:text-[140px] font-black tracking-tighter leading-[0.85] uppercase mb-12">
        LET'S BUILD <br/>SUCCESS.
      </h2>
      
      <p className="max-w-xl text-lg font-medium mb-12 opacity-80">
        Currently open to Administrative Lead, Project Management, and Design opportunities. 
        Let’s discuss how my blend of precision and creativity can help your team.
      </p>

      {/* Main CTA Button */}
      <a 
        href="mailto:beeokon68@gmail.com" 
        className="group relative px-12 py-6 bg-black text-white rounded-full overflow-hidden transition-all hover:scale-105 active:scale-95"
      >
        <span className="relative z-10 font-black tracking-widest text-sm uppercase">Get In Touch</span>
        <div className="absolute inset-0 bg-neutral-800 translate-y-full group-hover:translate-y-0 transition-transform duration-300" />
      </a>

      {/* Social Links & Secondary Info */}
      <div className="mt-24 w-full pt-10 border-t border-black/10 flex flex-col md:flex-row justify-between items-center gap-8">
        <div className="flex gap-8">
          {['LinkedIn', 'Instagram', 'Behance'].map((link) => (
            <a 
              key={link} 
              href="#" 
              className="text-xs font-black uppercase tracking-widest hover:opacity-50 transition-opacity"
            >
              {link}
            </a>
          ))}
        </div>

        <div className="text-right">
          <p className="text-[10px] font-mono uppercase tracking-[0.3em] opacity-60">
            © 2026 BLESSING OKON — ALL RIGHTS RESERVED
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
    </div>
  );
}